### ISSUE TITLE
Forking

### ISSUE THREAD

**Issue by dekken201** [benhoyt/pybktree#1]
Hello! I'm really interested in your implementation of BK Trees and am using this concept in a new project of mine. I'm kind of new to these GitHub terms and thought that forking would be what would be best applied in this situation. 
I want to get your code and make a few modifications to it so I can use in my project. Is it fine?  Feel free to contact me any way you want.

**Comment by benhoyt** [comment]
Sorry, just saw this now. Yes, if you want to "get my code and make a few modifications" that's exactly what forking is for. The [LICENSE](https://github.com/Jetsetter/pybktree/blob/master/LICENSE.txt) is a permissive MIT license so definitely allows for that. Go for it!

Or if you think the features you're adding would be of general interest, you could open an issue and discuss it here.
