### ISSUE TITLE
Request: Remove item

### ISSUE THREAD

**Issue by Jwink3101** [benhoyt/pybktree#6]
Is it possible to remove an item from the tree? I think that would add to the utility for larger projects.

Honestly, I may try to figure it out myself this weekend if I find the time. 

Thanks!

**Comment by benhoyt** [comment]
I'm not opposed to a `remove` method being added, particularly if you want to submit a good PR (with doctests). Thanks!

**Comment by Jwink3101** [comment]
A little digging says it is harder than expected. See for example https://stackoverflow.com/questions/42230648/deleting-a-node-in-a-bk-tree.

A way to kind of hack it is to keep track of removed items and exclude them from the results. However, I think that is probably not something that the base data structure should offer and should instead be done externally. 

I am going to close this. If inspiration strikes and I try and figure it out, I'll update but I am not hopeful.

Thanks!
